### ISSUE TITLE
[Feature] 增加网易云音乐外联播放器

### ISSUE THREAD

**Issue by StarrySky-skyler** [StarrySky-skyler/Share_And_Talk#3]

**Comment by StarrySky-skyler** [comment]
参考插入下面一段代码在html里
```html
<iframe id="fixed-iframe" frameborder="no" border="0" marginwidth="0" marginheight="0" width=330 height=86 src="//music.163.com/outchain/player?type=2&id=2102108609&auto=1&height=66"></iframe>
```
可以用css固定一下
```css
#fixed-iframe {
    position: fixed;
    right: 0;
    bottom: 0;
    width: 300px; /* 设置iframe宽度 */
    height: 200px; /* 设置iframe高度 */
    z-index: 999; /* 确保iframe在其他元素之上 */
}
```
